#!/usr/bin/env bash

echo -n "# 16 colors ############################"
echo "########################################"

T='gYw' # The test text

echo -n "                 40m     41m     42m     43m"
echo "     44m     45m     46m     47m"

for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
	'1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
	'  36m' '1;36m' '  37m' '1;37m'; do
	FG=${FGs// /}
	echo -en " $FGs \033[$FG  $T  "
	for BG in 40m 41m 42m 43m 44m 45m 46m 47m; do
		echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m"
	done
	echo
done
echo

echo -n "# 256 colors ###########################"
echo "########################################"
echo -en "   +  "
for i in {0..35}; do
	printf "%2b" "$i"
done

#for i in 16 52 88 124 160 196 232; do
for i in {0..6}; do
	i=$((i * 36 + 16))
	printf "\n %3b  " "$i"
	for j in {0..35}; do
		val=$((i + j))
		if [ "$val" -le 255 ]; then
			echo -en "\033[48;5;${val}m  \033[m"
		fi
	done
done
echo
echo

echo -n "# 24 bits ##############################"
echo "########################################"

width=78
#+BEGIN_SRC awk
awk -v term_cols="${width:-$(tput cols || echo 80)}" 'BEGIN{
    s="/\\";
    for (colnum = 0; colnum<term_cols; colnum++) {
        r = 255-(colnum*255/term_cols);
        g = (colnum*510/term_cols);
        b = (colnum*255/term_cols);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum%2+1,1);
    }
    printf "\n";
}'
#+END_SRC awk
